### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ahapsah30** [Area69Lab/Ubuntu-Grdp#9]
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
adduser: The group `chrome-remote-desktop' does not exist.
Error: Process completed with exit code 1.

**Comment by ElytrA8** [comment]
The official Support has been deprecated 

We aren't interested in fixing

**Comment by kumaryadav-prog1** [comment]
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> 
> Reading package lists...
> Building dependency tree...
> Reading state information...
> 0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
> adduser: The group `chrome-remote-desktop' does not exist.
> Error: Process completed with exit code 1.

Refer this: https://github.com/Area69Lab/Ubuntu-Grdp/pull/10/commits/d05ea444fdeb002443fc12b2175db2f225b56aa7

**Comment by ahapsah30** [comment]
> > WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> > Reading package lists...
> > Building dependency tree...
> > Reading state information...
> > 0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
> > adduser: The group `chrome-remote-desktop' does not exist.
> > Error: Process completed with exit code 1.
> 
> Refer this: [d05ea44](https://github.com/Area69Lab/Ubuntu-Grdp/commit/d05ea444fdeb002443fc12b2175db2f225b56aa7)

thnks bro

**Comment by nnippon** [comment]
Fixed re
